 # Wrangler configuration for Cloudflare Pages
name = "csv-transformer-hero"
compatibility_date = "2024-02-24"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

[site]
bucket = "./dist"

# Configure proper MIME types
[[headers]]
for = "/assets/*"
[headers.values]
Content-Type = "text/javascript"

[[headers]]
for = "/*"
[headers.values]
Content-Type = "text/javascript"