# Wrangler configuration for Cloudflare Workers with Static Assets
name = "excel-to-winfakt"
compatibility_date = "2024-02-24"
main = "src/worker.js"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"