// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujebouvijitxqazlvnfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqZWJvdXZpaml0eHFhemx2bmZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwOTA3NDAsImV4cCI6MjA0OTY2Njc0MH0.lBfslcWthy3nsncxd6H_B9j_JctzWxDZyStNqsXmK7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);